/**
 * College contracts shared by client and server.
 *
 * A college is the tenant. Only a university admin can create, edit, or deactivate one.
 */

export type CollegeDetail = {
  id: string;
  name: string;
  code: string;
  city: string;
  address: string;
  affiliationYear: number | null;
  isActive: boolean;
  createdAt: string;
};

/** A college plus the headcount behind it, for the university admin's list view. */
export type CollegeWithStats = CollegeDetail & {
  stats: {
    total: number;
    collegeAdmins: number;
    faculty: number;
    clerks: number;
    students: number;
  };
};

export type CreateCollegeRequest = {
  name: string;
  code: string;
  city?: string;
  address?: string;
  affiliationYear?: number;
};

export type UpdateCollegeRequest = Partial<CreateCollegeRequest>;

export type CreateCollegeAdminRequest = {
  email: string;
  firstName: string;
  middleName?: string;
  lastName: string;
};

/**
 * The response to creating a college admin.
 *
 * `temporaryPassword` is generated by the server and returned exactly once — it is never
 * stored in plain text and cannot be retrieved again. Generating it server-side avoids
 * the usual failure mode of one administrator inventing a weak password for another.
 */
export type CreateCollegeAdminResponse = {
  user: {
    id: string;
    email: string;
    fullName: string;
  };
  temporaryPassword: string;
};
